server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/example/Hospital/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

blockchain:
  ganache:
    url: http://localhost:7545
  contract:
    address: '0x179bE74Df87Abd819CfF03d2D48aBdf19943971F'
    abi: '''[
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "string",
        "name": "pid",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "transactionHash",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "RecordUpdated",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "name": "recordTxHashes",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function",
    "constant": true
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_pid",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_transactionHash",
        "type": "string"
      }
    ],
    "name": "setRecordTxHash",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_pid",
        "type": "string"
      }
    ],
    "name": "getRecordTxHash",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function",
    "constant": true
  }
]'''
  wallet:
    privateKey: '0xd7dcbdbbdd0445d429ba91ad63d54d24e49287c55c8c00e75a116dbc06ba7fd3'

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'bed'
      paths-to-match: '/bed/**'
    - group: 'drug'
      paths-to-match: '/drug/**'
    - group: 'finance'
      paths-to-match: '/finance/**'
    - group: 'patient'
      paths-to-match: '/patient/**'
    - group: 'treatment'
      paths-to-match: '/treatment/**'
    - group: 'user'
      paths-to-match: '/user/**'
    - group: 'work'
      paths-to-match: '/work/**'
    - group: 'brain'
      paths-to-match: '/braintumor/**'
    - group: 'chat'
      paths-to-match: '/medicalmodel/**'
    - group: 'block'
      paths-to-match: '/blockchain-work/**'

knife4j:
  enable: true
  setting:
    language: zh_cn